// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc5SNZS2D5_89N4an_KqlnvKrGDntFcPA',
    appId: '1:159491812956:web:82ea7a58ee904f746b8099',
    messagingSenderId: '159491812956',
    projectId: 'ecommerce-2831d',
    authDomain: 'ecommerce-2831d.firebaseapp.com',
    storageBucket: 'ecommerce-2831d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhTcVx42e2A0Attx3BcYHrRp6YwfX5rcQ',
    appId: '1:159491812956:android:c3c1667926b851126b8099',
    messagingSenderId: '159491812956',
    projectId: 'ecommerce-2831d',
    storageBucket: 'ecommerce-2831d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiQLROQzwvSktbP6qyiFQggBkhtPLbW2w',
    appId: '1:159491812956:ios:6ff5603c1c13b4916b8099',
    messagingSenderId: '159491812956',
    projectId: 'ecommerce-2831d',
    storageBucket: 'ecommerce-2831d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiQLROQzwvSktbP6qyiFQggBkhtPLbW2w',
    appId: '1:159491812956:ios:6ff5603c1c13b4916b8099',
    messagingSenderId: '159491812956',
    projectId: 'ecommerce-2831d',
    storageBucket: 'ecommerce-2831d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceCustomer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc5SNZS2D5_89N4an_KqlnvKrGDntFcPA',
    appId: '1:159491812956:web:f281765965fdedc66b8099',
    messagingSenderId: '159491812956',
    projectId: 'ecommerce-2831d',
    authDomain: 'ecommerce-2831d.firebaseapp.com',
    storageBucket: 'ecommerce-2831d.firebasestorage.app',
  );

}